# Generated by Django 3.0.5 on 2020-04-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a field (e.g. Physics) ', max_length=200)),
                ('info', models.CharField(help_text='Enter some info about the field', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('born_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'username', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Postedby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField(help_text='Enter a brief description of the course', max_length=1000)),
                ('field', models.ManyToManyField(help_text='Select a field for this course', to='catalog.Field')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Users')),
            ],
        ),
    ]
