# Generated by Django 3.0.5 on 2020-04-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200415_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Postedby',
        ),
        migrations.AlterModelOptions(
            name='postedby',
            options={'verbose_name_plural': 'Posted by'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
