# Generated by Django 3.0.5 on 2020-05-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_mycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.User'),
        ),
    ]
