# Generated by Django 3.0.5 on 2020-05-27 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200513_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedby',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Course'),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.User'),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Course'),
        ),
    ]
