# Generated by Django 3.0.5 on 2020-06-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_lessons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name_plural': 'Lessons'},
        ),
        migrations.AddField(
            model_name='lessons',
            name='text',
            field=models.TextField(default='', help_text='Helping text or other infomartion that you want on display', max_length=10000),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='title',
            field=models.TextField(help_text='Lesson title', max_length=150),
        ),
    ]
