# Generated by Django 3.0.5 on 2020-06-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200628_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Not started'), ('i', 'Incomplete'), ('c', 'Completed')], default='n', help_text='Courses taken', max_length=1),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='arxeio',
            field=models.FileField(upload_to='media'),
        ),
    ]
