# Generated by Django 3.0.8 on 2020-07-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200718_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['order'], 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AddField(
            model_name='lessons',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
