# Generated by Django 3.1 on 2020-10-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20201003_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='badg/')),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.badges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
    ]
