# Generated by Django 3.1 on 2020-10-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_badges_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.user'),
        ),
    ]
