# Generated by Django 3.1 on 2020-10-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20201004_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank_status',
            field=models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum'), (5, 'Diamond'), (6, 'Master'), (7, 'GrandMaster')], default=1, help_text='User Rank'),
        ),
    ]
